gem 'omniauth-google-oauth2'
gem 'honeybadger'
gem 'stripe'
gem 'stripe_event'
gem 'sidekiq'

group :development do
  gem 'guard'
  gem 'guard-livereload', '~> 2.5', require: false
  gem 'rack-livereload'
  gem 'solargraph-rails', '0.2.0.pre'
end