--- !ruby/object:Jumpstart::Configuration
application_name: Billsly
business_name: Billsly, LLC
domain: billsly.co
support_email: hello@billsly.co
default_from_email: Billsly hello@billsly.co>
business_address: ''
background_job_processor: sidekiq
email_provider: sendgrid
personal_accounts: true
livereload: true
solargraph: true
register_with_account: false
integrations:
- honeybadger
payment_processors:
- stripe
