# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
# Place this file at config/sidekiq.yml and Sidekiq will
# pick it up automatically.
---
:verbose: false
:concurrency: 10

# Set timeout to 8 on Heroku, longer if you manage your own systems.
:timeout: 30

# Sidekiq will run this file through ERB when reading it so you can
# even put in dynamic logic, like a host-specific queue.
# http://www.mikeperham.com/2013/11/13/advanced-sidekiq-host-specific-queues/
:queues:
  - critical
  - default
  - <%= `hostname`.strip %>
  - mailers
  - low

# you can override concurrency based on environment
production:
  :concurrency: 25
  :timeout: 8
  :configure_client:
    - url
      - <%= ENV['REDIS_URL'] %>
    - ssl_params
      - verify_mode
        - OpenSSL::SSL::VERIFY_NONE
  :configure_server:
    - url
      - <%= ENV['REDIS_URL'] %>
    - ssl_params
      - verify_mode
        - OpenSSL::SSL::VERIFY_NONE
  
staging:
  :concurrency: 15
